# Generated by Django 6.1.1 on 2026-09-28 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(choices=[('Consulta Clínica', 'Consulta Clínica'), ('Vacinação', 'Vacinação'), ('Retorno', 'Retorno'), ('Procedimento', 'Procedimento'), ('Coleta de Exames', 'Coleta de Exames')], max_length=50)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('duracao_minutos', models.IntegerField(default=60)),
                ('endereco', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Confirmado', 'Confirmado'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], default='Agendado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
    ]
