# Generated by Django 6.1.1 on 2026-09-28 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('data_aplicacao', models.DateField()),
                ('lote', models.CharField(max_length=50)),
                ('validade', models.DateField()),
                ('proxima_dose', models.DateField(blank=True, null=True)),
                ('veterinaria_responsavel', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
    ]
